# Generated by Django 5.0.1 on 2024-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='registration/img/no-avatar.jpg', upload_to='members'),
        ),
    ]
